<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U2QK182" failures="1" tests="1" name="Test" time="22.793" errors="0" timestamp="2023-02-06T19:46:31 IST">
  <testcase classname="siddemo.tests.Standolonetest2" name="SubmitOrder" time="14.443">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER....] but found [THANKYOU FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER....] but found [THANKYOU FOR THE ORDER.]
at siddemo.tests.Standolonetest2.SubmitOrder(Standolonetest2.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SubmitOrder -->
</testsuite> <!-- Test -->
